### PR TITLE
Update to Chrome 59 API

### PR DESCRIPTION
**Pull request by roehling**
Tested under ROS Kinetic

### CODE REVIEW

**Comment by SystemDiagnosticss** [comment]
@roehling Hello. I can't install your fork .. 
28308797_1822309257833516_882020111_n
Maybe did you have solution?

**Comment by roehling** [comment]
I think I installed the `webrtc` package and did not try to use it from the devel space. Honestly, it has been a while, and I actually created a `ros-kinetic-webrtc` Ubuntu package that installs to `/opt/ros/kinetic`, because it takes so long to build and you need to download gigabytes of source code...

If you want to have a look, the  `webrtcConfig.cmake` is generated [here](https://github.com/RobotWebTools/webrtc_ros/pull/34/files#diff-471100f0d39cadf73ed7576812614151R51) and installed [here](https://github.com/RobotWebTools/webrtc_ros/pull/34/files#diff-abe39c5c3b50e0d7c77287706f79f27fR58).

**Comment by vzts** [comment]
@roehling Hello, thank you for the PR! Have you made it work at the time? I'm trying to use your patch to start.

**Comment by roehling** [comment]
It works for me if I build `webrtc` first, without `webrtc_ros`. Also, I do not use`catkin_make`; I prefer to build my ROS packages with [catkin_tools](https://catkin-tools.readthedocs.io/en/latest/).

**Comment by jihoonl** [comment]
Hi @roehling, I put you as an admin of this repo. Feel free to manage as you like.

**Comment by vzts** [comment]
Thank you all for the great open source efforts!
I as well will make contributions if there is any along the way I harness this project. Thank you again!

**Comment by roehling** [comment]
I will prepare a ROS release, but first I'm trying to reduce the required download as much as possible.

**Pull request merged**
